blank_issues_enabled: true
contact_links:
  - name: 💬 General Discussion
    url: https://github.com/rol2005hun/Streamletz/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📖 Documentation
    url: https://github.com/rol2005hun/Streamletz/blob/master/README.md
    about: Check out our documentation